= GRAFFL
:toc:

== Basic Structure

*graffl* produces *RDF* statements consisting of subject, predicate and objects.

The basic structure:

. Directives starting with `@`
. Blocks
. Optional group graphs

A __block__ starts with a subject followed by predicate-object pairs.
The block is terminated with empty line:

----
@ prefix <http://example.org/ns#>

  Alice email alice@example.org
    likes -> Bob

  Bob email bob@example.org
    likes -> Alice
----

An object produces a literal unless:

- the object is a URI like `<mailto:alice@example.org>`
- the object has been defined to be an __alias__ (see below)
- the predicate has been specified to be a  __URI property__ (see below)
- the predicate is followed by an arrow `++->++` making the predicate a __relation__

== Nodes

`Alice`: A node with label `Alice`

`"Mr. Bean"`: A node with label `Mr. Bean`

`"""Mr. Bean"""`: A node with label `Mr. Bean`

`(my node)`: A node reference, no explicit label

`\<https://example.org>`: A node with specified URI, no explicit label

If the label is a word without whitespace like "Alice", then `Alice`, `(Alice)`, `"Alice"` or `"""Alice"""` all refer to the same node.

== Aliases

Every word can be an __alias__ for a URI.
For defining an alias in the script use an assginment `=` in a directive:

----
@ x = <http://www.example.org/x>
@ y = <http://fowf#y>
@ z = <urn:z>

x y z
----

Here is a list of predefined aliases (see also the code of `src/graffl/config.py`):

|===
| `:`, `type` | rdf:type
| `=` , `value`    | rdf:value
| `Property`       | rdf:Property
| `Datatype`       | rdf:Datatype
| `Alt`            | rdf:Alt
| `Bag`            | rdf:Bag
| `Seq`            | rdf:Seq
| `*`              | rdf:li
| `Class`          | rdfs:Class
| `label`          | rdfs:label
| `;`, `comment`   | rdfs:comment
| `subClassOf`     | rdfs:subClassOf
| `subPropertyOf`  | rdfs:subPropertyOf
| `seeAlso`        | rdfs:seeAlso
| `isDefinedBy`    | rdfs:isDefinedBy
|===

== URI Properties

Sometimes a predicate is considered a property but its value shall be an individual.
Then a predicate can be specified to be a __URI property__ by assigning it a `URI` type:

----
@ state : URI

Alice state ACTIVE
----

The produced RDF as __Turtle__:

----
@prefix ns1: <https://www.hedenus.de/graffl/5e7a8688-3705-11f1-b85e-e08f4ccbe174/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

ns1:Alice rdfs:label "Alice" ;
    ns1:state ns1:ACTIVE .
----

Predefined _URI properties_ are (see also the code of `src/graffl/config.py`):

* `rdf:type`
* `rdfs:subClassOf`
* all *OWL* properties

== Datatypes

TODO...

== Blank Nodes

Objects may be __blank nodes__.
They are surrounded by square brackets and look very much like __Turtle__:

-----
Alice fullName [
        firstName "Alice"
        secondName "Jane"
        lastName "Van Houten"
    ]
-----

== Containers

By default `*` is a predefined __alias__ for `rdf:li`.

A numbering `nnn.`, where nnn is any positive integer number, produces `rdf:_nnn`:

----
(Tasks)
  1. Beginn
  2. "do something"
  99. Done
----

The produced RDF as __Turtle__:

----
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<https://www.hedenus.de/graffl/8e91d8f4-3707-11f1-bfb6-e08f4ccbe174/Tasks> rdf:_1 "Beginn" ;
    rdf:_2 "do something" ;
    rdf:_99 "Done" .
----

== Lists (Collections)

A list (i.e. a rdf:List) starts with `*(` and ends with `)`. The predicate type is applied to the list members.
For example:

----
Rainbow colors *( Red Green Blue )
----

will regard the colors as literals whereas

----
Rainbow colors -> *( Red Green Blue )
----

will regard the colors as nodes.

=== OWL Modeling

The *OWL* vocabulary is predefined as _URI properties_. This make writing an ontology simple:

----
@prefix <http://example.org/pizza#>

SalamiPizza
    : Class
    subClassOf [
        : Class
        intersectionOf *(
            Pizza
            [
                : Restriction
                onProperty hasTopping
                someValuesFrom Salami
            ]
            [
                : Restriction
                onProperty hasTopping
                someValuesFrom Mozzarella
            ]
        )
    ]
----

== Languages

An object may be tagged with an ISO 639 language code:

-----
(a) label @en Alice
    label @tlh QelIS
-----

== Base URI Prefix

The directive `@prefix` defines the base URI prefix.
It is called "prefix" because the resulting URI is a simple concatenation of the prefix with the encoded node label:

-----
@prefix <http://example.org/ns#>

"Mr. Bean"
-----

produces the URI `++<http://example.org/ns#Mr.%20Bean>++`.

The default URI prefix is `++https://www.hedenus.de/graffl/++` plus a runtime UUID, i.e. every parser run will create new unique URIs for the nodes.
Define a custom prefix for reproducible URIs.

== Group Graphs

__Group graphs__ provide a simple and visual way to cluster statements into logical groups or contexts.
A __group graph__ begins with a header containing the group's name enclosed by `----` (at least four minus characters) and ends with a closing line of `----` (at least four minus characters).
Any node that appears as a subject within these boundaries is automatically linked as being contained by the group.

**Important Note on Nesting:**
The `graffl` syntax does *not* allow you to physically nest one group graph block inside another.
Trying to open a new group graph before closing the current one will result in a syntax error.

Instead, to model hierarchical structures or logical nesting, you must define the group blocks **side by side**.
You can then establish the hierarchy by simply using a child group's name as a subject within the parent group's block, or by linking them with explicit relations.

=== Simple Groups

A __group graph__ header is a node enclosed by  `----`  (at least four minus characters).
It ends with again `----` (at least four minus characters).
A node is contained by the __group graph__ if it appears as subject within its boundaries.
__Group graphs__ may contain other __group graphs__.
However, nested descriptions are not allowed; instead, they must be described side by side.

=== Simple Groups

For example, consider two teams `Team-1` and `Team-2`.
Alice and Bob are in the first, Chris and David the second team.
The teams are working together and both are part of the Agile Release Train.
You can write this down as follows:

----

---- Team-1 ----
    Alice

    Bob
----------------

Team-1 worksWith -> Team-2

---- Team-2 ----
    Chris

    David
----------------

---- The Agile Release Train ----

    Team-1

    Team-2

--------------------------------
----

The produced RDF as __Turtle__:

----
@prefix ns1: <https://www.hedenus.de/graffl/> .
@prefix ns2: <https://www.hedenus.de/graffl/9edf4a14-366c-11f1-8458-e08f4ccbe174/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

ns2:Team-1 a ns1:Group ;
    rdfs:label "Team-1" ;
    ns2:worksWith ns2:Team-2 ;
    ns1:contains ns2:Alice,
        ns2:Bob .

ns2:Team-2 a ns1:Group ;
    rdfs:label "Team-2" ;
    ns1:contains ns2:Chris,
        ns2:David .

ns2:The%20Agile%20Release%20Train a ns1:Group ;
    rdfs:label "The Agile Release Train" ;
    ns1:contains ns2:Team-1,
        ns2:Team-2 .


ns2:Alice rdfs:label "Alice" .

ns2:Bob rdfs:label "Bob" .

ns2:Chris rdfs:label "Chris" .

ns2:David rdfs:label "David" .
----

=== Hierarchical Modeling

One important application of this feature is for __breaking down__ things into different levels of details.
For example, imaging a battery holder which contains three batteries.
These batteries are all instances of the same class and have the same inner structure.
The inners structure of a battery is in the is example modeled as connection points and electrochemistry:

----

System : Class

BatteryHolder subClassOf System

Battery subClassOf System

ConnectionPoint subClassOf System

Electrochemistry subClassOf System


---- BatteryHolder ----

b1 : Battery

b2 : Battery

b3 : Battery

b1 connectedTo -> b2

b2 connectedTo -> b3

-----------------------


---- Battery ----------------------------

plus : ConnectionPoint

minus : ConnectionPoint

electrochemistry : Electrochemistry

minus electricFlow -> electrochemistry

electrochemistry electricFlow -> plus

-----------------------------------------

----
