= GRAFFL

=== Basic Structure

*graffl* produces RDF statements consisting of subject, predicate and objects.

The basic structure is a __block__ starting with a subject followed by predicate-object pairs.
The block is terminated with empty line.

----
  Alice email alice@example.org
    likes -> Bob

  Bob email bob@example.org
    likes -> Alice
----

An object is a literal unless

- the object is  URI like `<mailto:alice@example.org>`
- the object is specified as `uri_property`
- the predicate is followed by an arrow `+++->+++` making the pedicate a __relation__

=== Nodes

`Alice`: A node with label `Alice`

`"Mr. Bean"`:  A node with label `Mr. Bean`

`"""Mr. Bean"""`:  A node with label `Mr. Bean`

`(my node)`: A node refence, no explicit label

`\<https://example.org>`: A node with specified URI, no explicit label

If the label is a word without whitespace like "Alice",
then `Alice`, `(Alice)`, `"Alice"` or `"""Alice"""` all refer to the same node.

=== Special Properties

`NNN.` where NNN is any non-negative number is read as `rdf:_NNN`

==== Aliases

Every word can be an __alias__ for a URI.
See the code `src/graffl/config.py` for the current list of predefined aliases.

|===
| `:`, `a`, `type` | rdf:type
| `=` , `value`    | rdf:value
| `Property`       | rdf:Property
| `Alt`            | rdf:Alt
| `Bag`            | rdf:Bag
| `Seq`            | rdf:Seq
| `*`              | rdf:li
| `Class`          | rdfs:Class
| `label`          | rdfs:label
| `;`, `comment`   | rdfs:comment
| `subClassOf`     | rdfs:subClassOf
| `subPropertyOf`  | rdfs:subPropertyOf
|===


=== Directives

Directives are at the beginning of the script.
The start with `@`.

For example:
-----
@prefix http://example.org/my#

Alice
-----

defines the URI prefix attached the node label.
In this case the resulting URI is `\<http://example.org/my#Alice>`.
(It is called "prefix" because it is a simple concatenation.)