= GRAFFL

=== Basic Structure

*graffl* produces RDF statements consisting of subject, predicate and objects.

The basic structure:

. Directives starting with `@`
. Blocks
. Optional group graphs

A __block__ starts with a subject followed by predicate-object pairs.
The block is terminated with empty line.

----
@ prefix <http://example.org/ns#>

  Alice email alice@example.org
    likes -> Bob

  Bob email bob@example.org
    likes -> Alice
----

An object is a literal unless

- the object is  URI like `<mailto:alice@example.org>`
- the object is specified as `uri_property`
- the predicate is followed by an arrow `+++->+++` making the pedicate a __relation__

=== Nodes

`Alice`: A node with label `Alice`

`"Mr. Bean"`:  A node with label `Mr. Bean`

`"""Mr. Bean"""`:  A node with label `Mr. Bean`

`(my node)`: A node refence, no explicit label

`\<https://example.org>`: A node with specified URI, no explicit label

If the label is a word without whitespace like "Alice",
then `Alice`, `(Alice)`, `"Alice"` or `"""Alice"""` all refer to the same node.

=== ContainerMembershipProperty

`NNN.`, where NNN is any non-negative integer number, produces `rdf:_NNN`, e.g.:

----
    Tasks
      1. Beginn
      2. "do something"
      3. Done
----

==== Aliases

Every word can be an __alias__ for a URI.
For defining an alias in the script use an assginment in an directive, e.g.:

----
@ x = <http://example.org/data/x>

x y -> z
----



See the code `src/graffl/config.py` for the current list of predefined aliases.

|===
| `:`, `a`, `type` | rdf:type
| `=` , `value`    | rdf:value
| `Property`       | rdf:Property
| `Datatype`       | rdf:Datatype
| `Alt`            | rdf:Alt
| `Bag`            | rdf:Bag
| `Seq`            | rdf:Seq
| `*`              | rdf:li
| `Class`          | rdfs:Class
| `label`          | rdfs:label
| `;`, `comment`   | rdfs:comment
| `subClassOf`     | rdfs:subClassOf
| `subPropertyOf`  | rdfs:subPropertyOf
| `seeAlso`        | rdfs:seeAlso
| `isDefinedBy`    | rdfs:isDefinedBy
|===


=== Base URI Prefix

The directive `@prefix` defines the base URI prefix.
It is called "prefix" because the resulting URI is a simple concatenation
of the prefix with the encoded node label.

For example:
-----
@prefix <http://example.org/ns#>

"Mr. Bean"
-----

produces the URI `\<http://example.org/ns#Mr.%20Bean> `.