import logging

from rdflib import OWL
from rdflib.namespace import XSD

logger = logging.getLogger(__name__)


class GrafflConfig:
    def __init__(self):
        self.base_uri = "https://www.hedenus.de/graffl/"

        self.dictionary = {
            # --- RDF Core ---
            ":": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            "type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            "=": "http://www.w3.org/1999/02/22-rdf-syntax-ns#value",
            "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#value",
            "Property": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
            "*": "http://www.w3.org/1999/02/22-rdf-syntax-ns#li",
            "Alt": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt",
            "Bag": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag",
            "Seq": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq",

            # --- RDFS Core ---
            "rdfsClass": "http://www.w3.org/2000/01/rdf-schema#Class",
            "Datatype": "http://www.w3.org/2000/01/rdf-schema#Datatype",
            "label": "http://www.w3.org/2000/01/rdf-schema#label",
            "comment": "http://www.w3.org/2000/01/rdf-schema#comment",
            ";": "http://www.w3.org/2000/01/rdf-schema#comment",
            "subClassOf": "http://www.w3.org/2000/01/rdf-schema#subClassOf",
            "subPropertyOf": "http://www.w3.org/2000/01/rdf-schema#subPropertyOf",
            "seeAlso": "http://www.w3.org/2000/01/rdf-schema#seeAlso",
            "isDefinedBy": "http://www.w3.org/2000/01/rdf-schema#isDefinedBy",

            # --- OWL Full ---
            "AllDifferent": OWL.AllDifferent,
            "AllDisjointClasses": OWL.AllDisjointClasses,
            "AllDisjointProperties": OWL.AllDisjointProperties,
            "Annotation": OWL.Annotation,
            "AnnotationProperty": OWL.AnnotationProperty,
            "AsymmetricProperty": OWL.AsymmetricProperty,
            "Axiom": OWL.Axiom,
            "Class": OWL.Class,
            "DataRange": OWL.DataRange,
            "DatatypeProperty": OWL.DatatypeProperty,
            "DeprecatedClass": OWL.DeprecatedClass,
            "DeprecatedProperty": OWL.DeprecatedProperty,
            "FunctionalProperty": OWL.FunctionalProperty,
            "InverseFunctionalProperty": OWL.InverseFunctionalProperty,
            "IrreflexiveProperty": OWL.IrreflexiveProperty,
            "NamedIndividual": OWL.NamedIndividual,
            "NegativePropertyAssertion": OWL.NegativePropertyAssertion,
            "Nothing": OWL.Nothing,
            "ObjectProperty": OWL.ObjectProperty,
            "Ontology": OWL.Ontology,
            "OntologyProperty": OWL.OntologyProperty,
            "ReflexiveProperty": OWL.ReflexiveProperty,
            "Restriction": OWL.Restriction,
            "SymmetricProperty": OWL.SymmetricProperty,
            "Thing": OWL.Thing,
            "TransitiveProperty": OWL.TransitiveProperty,

            "allValuesFrom": OWL.allValuesFrom,
            "annotatedProperty": OWL.annotatedProperty,
            "annotatedSource": OWL.annotatedSource,
            "annotatedTarget": OWL.annotatedTarget,
            "assertionProperty": OWL.assertionProperty,
            "backwardCompatibleWith": OWL.backwardCompatibleWith,
            "bottomDataProperty": OWL.bottomDataProperty,
            "bottomObjectProperty": OWL.bottomObjectProperty,
            "cardinality": OWL.cardinality,
            "complementOf": OWL.complementOf,
            "datatypeComplementOf": OWL.datatypeComplementOf,
            "deprecated": OWL.deprecated,
            "differentFrom": OWL.differentFrom,
            "disjointUnionOf": OWL.disjointUnionOf,
            "disjointWith": OWL.disjointWith,
            "distinctMembers": OWL.distinctMembers,
            "equivalentClass": OWL.equivalentClass,
            "equivalentProperty": OWL.equivalentProperty,
            "hasKey": OWL.hasKey,
            "hasSelf": OWL.hasSelf,
            "hasValue": OWL.hasValue,
            "imports": OWL.imports,
            "incompatibleWith": OWL.incompatibleWith,
            "intersectionOf": OWL.intersectionOf,
            "inverseOf": OWL.inverseOf,
            "maxCardinality": OWL.maxCardinality,
            "maxQualifiedCardinality": OWL.maxQualifiedCardinality,
            "members": OWL.members,
            "minCardinality": OWL.minCardinality,
            "minQualifiedCardinality": OWL.minQualifiedCardinality,
            "onClass": OWL.onClass,
            "onDataRange": OWL.onDataRange,
            "onDatatype": OWL.onDatatype,
            "onProperties": OWL.onProperties,
            "onProperty": OWL.onProperty,
            "oneOf": OWL.oneOf,
            "priorVersion": OWL.priorVersion,
            "propertyChainAxiom": OWL.propertyChainAxiom,
            "propertyDisjointWith": OWL.propertyDisjointWith,
            "qualifiedCardinality": OWL.qualifiedCardinality,
            "sameAs": OWL.sameAs,
            "someValuesFrom": OWL.someValuesFrom,
            "sourceIndividual": OWL.sourceIndividual,
            "targetIndividual": OWL.targetIndividual,
            "targetValue": OWL.targetValue,
            "topDataProperty": OWL.topDataProperty,
            "topObjectProperty": OWL.topObjectProperty,
            "unionOf": OWL.unionOf,
            "versionIRI": OWL.versionIRI,
            "versionInfo": OWL.versionInfo,
            "withRestrictions": OWL.withRestrictions,

            # --- rdf2graphml ---
            "color": "https://www.hedenus.de/rdf2graphml/color",
            "shape": "https://www.hedenus.de/rdf2graphml/shape",
            "icon": "https://www.hedenus.de/rdf2graphml/icon",
            "lineType": "https://www.hedenus.de/rdf2graphml/lineType",
            "targetArrow": "https://www.hedenus.de/rdf2graphml/targetArrow"
        }

        self.uri_properties = {
            "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
            "http://www.w3.org/2000/01/rdf-schema#subClassOf",
            "http://www.w3.org/2002/07/owl#allValuesFrom",
            "http://www.w3.org/2002/07/owl#annotatedProperty",
            "http://www.w3.org/2002/07/owl#annotatedSource",
            "http://www.w3.org/2002/07/owl#annotatedTarget",
            "http://www.w3.org/2002/07/owl#assertionProperty",
            "http://www.w3.org/2002/07/owl#backwardCompatibleWith",
            "http://www.w3.org/2002/07/owl#bottomDataProperty",
            "http://www.w3.org/2002/07/owl#bottomObjectProperty",
            "http://www.w3.org/2002/07/owl#cardinality",
            "http://www.w3.org/2002/07/owl#complementOf",
            "http://www.w3.org/2002/07/owl#datatypeComplementOf",
            "http://www.w3.org/2002/07/owl#deprecated",
            "http://www.w3.org/2002/07/owl#differentFrom",
            "http://www.w3.org/2002/07/owl#disjointUnionOf",
            "http://www.w3.org/2002/07/owl#disjointWith",
            "http://www.w3.org/2002/07/owl#distinctMembers",
            "http://www.w3.org/2002/07/owl#equivalentClass",
            "http://www.w3.org/2002/07/owl#equivalentProperty",
            "http://www.w3.org/2002/07/owl#hasKey",
            "http://www.w3.org/2002/07/owl#hasSelf",
            "http://www.w3.org/2002/07/owl#hasValue",
            "http://www.w3.org/2002/07/owl#imports",
            "http://www.w3.org/2002/07/owl#incompatibleWith",
            "http://www.w3.org/2002/07/owl#intersectionOf",
            "http://www.w3.org/2002/07/owl#inverseOf",
            "http://www.w3.org/2002/07/owl#maxCardinality",
            "http://www.w3.org/2002/07/owl#maxQualifiedCardinality",
            "http://www.w3.org/2002/07/owl#members",
            "http://www.w3.org/2002/07/owl#minCardinality",
            "http://www.w3.org/2002/07/owl#minQualifiedCardinality",
            "http://www.w3.org/2002/07/owl#onClass",
            "http://www.w3.org/2002/07/owl#onDataRange",
            "http://www.w3.org/2002/07/owl#onDatatype",
            "http://www.w3.org/2002/07/owl#onProperties",
            "http://www.w3.org/2002/07/owl#onProperty",
            "http://www.w3.org/2002/07/owl#oneOf",
            "http://www.w3.org/2002/07/owl#priorVersion",
            "http://www.w3.org/2002/07/owl#propertyChainAxiom",
            "http://www.w3.org/2002/07/owl#propertyDisjointWith",
            "http://www.w3.org/2002/07/owl#qualifiedCardinality",
            "http://www.w3.org/2002/07/owl#sameAs",
            "http://www.w3.org/2002/07/owl#someValuesFrom",
            "http://www.w3.org/2002/07/owl#sourceIndividual",
            "http://www.w3.org/2002/07/owl#targetIndividual",
            "http://www.w3.org/2002/07/owl#targetValue",
            "http://www.w3.org/2002/07/owl#topDataProperty",
            "http://www.w3.org/2002/07/owl#topObjectProperty",
            "http://www.w3.org/2002/07/owl#unionOf",
            "http://www.w3.org/2002/07/owl#versionIRI",
            "http://www.w3.org/2002/07/owl#versionInfo",
            "http://www.w3.org/2002/07/owl#withRestrictions",
        }

        self.xsd_types = {
            "anyURI": XSD.anyURI,
            "base64Binary": XSD.base64Binary,
            "boolean": XSD.boolean,
            "byte": XSD.byte,
            "date": XSD.date,
            "dateTime": XSD.dateTime,
            "dateTimeStamp": XSD.dateTimeStamp,
            "dayTimeDuration": XSD.dayTimeDuration,
            "decimal": XSD.decimal,
            "double": XSD.double,
            "duration": XSD.duration,
            "float": XSD.float,
            "gDay": XSD.gDay,
            "gMonth": XSD.gMonth,
            "gMonthDay": XSD.gMonthDay,
            "gYear": XSD.gYear,
            "gYearMonth": XSD.gYearMonth,
            "hexBinary": XSD.hexBinary,
            "int": XSD.int,
            "integer": XSD.integer,
            "long": XSD.long,
            "negativeInteger": XSD.negativeInteger,
            "nonNegativeInteger": XSD.nonNegativeInteger,
            "nonPositiveInteger": XSD.nonPositiveInteger,
            "positiveInteger": XSD.positiveInteger,
            "short": XSD.short,
            "string": XSD.string,
            "time": XSD.time,
            "unsignedByte": XSD.unsignedByte,
            "unsignedInt": XSD.unsignedInt,
            "unsignedLong": XSD.unsignedLong,
            "unsignedShort": XSD.unsignedShort,
            "yearMonthDuration": XSD.yearMonthDuration
        }

        self.group_contains = "https://www.hedenus.de/graffl/contains"
        self.group_type = "https://www.hedenus.de/graffl/Group"


CONFIG = GrafflConfig()
